### PR TITLE
Allow unzipped files too

### PR DESCRIPTION
**Pull request by rbiswas4**
While this was designed to deal with zipped files, it is easy to extend it to take 'zipped' as an optional parameter. For the default value of this parameter `True`, the previous behavior is recovered. If it is set to `False`, it simply reads the unzipped files.

### CODE REVIEW

**Comment by djreiss** [comment]
Another option would be to check if the filename ends in ".gz" and if so, use `gzip` to open it.

**Comment by djreiss** [comment]
Do you have any objection to my suggestion on this? If so I'll implement it that way, negating the need for the "zipped" option.

**Comment by djreiss** [comment]
I'll just merge your changes as-is for now.

**Comment by rbiswas4** [comment]
Not at all!

**Pull request merged**
